name: 'Sphinx docs to GitHub Pages'
description: 'Automatic Sphinx html docs compilation and deployment through the gh-pages branch.'
author: "Diego Prada"
branding:
  icon: "upload-cloud"
  color: "orange"
runs:
  using: "composite"
  steps:
    - name: setting the committer name and email
      id: committer
      run: bash $GITHUB_ACTION_PATH/set_committer.sh
      shell: bash
    - name: gh-pages branch creation if needed
      id: gh-pages-branch-creation
      run: bash $GITHUB_ACTION_PATH/gh-pages_branch.sh
      shell: bash
    - name: make conda environment
      id: conda-env
      uses: conda-incubator/setup-miniconda@v2    # https://github.com/conda-incubator/setup-miniconda
      with:
        environment-file: devtools/conda-envs/docs_env.yaml
        activate-environment: docs
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true

